// <auto-generated />
using System;
using App.infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.infra.Persistence.Migrations.ReadDb
{
    [DbContext(typeof(AppReadDbContext))]
    [Migration("20260827192612_AddHomeworkSystemToReadDb")]
    partial class AddHomeworkSystemToReadDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.domain.ReadModels.AdvertisementRead", b =>
                {
                    b.Property<string>("Advertisement_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Advertisement_id");

                    b.ToTable("AdvertisementsRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.CourseContentRead", b =>
                {
                    b.Property<string>("Content_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Content_id");

                    b.ToTable("CourseContentsRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.CourseRead", b =>
                {
                    b.Property<string>("Course_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Course_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Course_id");

                    b.ToTable("CoursesRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.CourseStudentRead", b =>
                {
                    b.Property<string>("Student_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Course_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FinalMark")
                        .HasColumnType("float");

                    b.Property<double?>("FirstExamMark")
                        .HasColumnType("float");

                    b.Property<double?>("SecondExamMark")
                        .HasColumnType("float");

                    b.Property<double?>("WorkMark")
                        .HasColumnType("float");

                    b.HasKey("Student_id", "Course_id");

                    b.ToTable("EnrollmentsRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.EmployeeRead", b =>
                {
                    b.Property<string>("Employee_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employee_id");

                    b.ToTable("EmployeesRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.HomeworkQuestionMarkRead", b =>
                {
                    b.Property<string>("QuestionMark_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("MaxMarks")
                        .HasColumnType("float");

                    b.Property<double?>("ObtainedMarks")
                        .HasColumnType("float");

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Submission_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionMark_id");

                    b.ToTable("HomeworkQuestionMarksRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.HomeworkRead", b =>
                {
                    b.Property<string>("Homework_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Course_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionFileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.HasKey("Homework_id");

                    b.ToTable("HomeworksRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.HomeworkSolutionRead", b =>
                {
                    b.Property<string>("Solution_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Homework_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionFileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Solution_id");

                    b.ToTable("HomeworkSolutionsRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.HomeworkSubmissionRead", b =>
                {
                    b.Property<string>("Submission_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Homework_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Mark")
                        .HasColumnType("float");

                    b.Property<string>("SolutionFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionFileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Submission_id");

                    b.ToTable("HomeworkSubmissionsRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.InstructorRead", b =>
                {
                    b.Property<string>("Instructor_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Instructor_id");

                    b.ToTable("InstructorsRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.StudentRead", b =>
                {
                    b.Property<string>("Student_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_id");

                    b.ToTable("StudentsRead");
                });
#pragma warning restore 612, 618
        }
    }
}
