// <auto-generated />
using System;
using App.infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.infra.Persistence.Migrations.ReadDb
{
    [DbContext(typeof(AppReadDbContext))]
    [Migration("20260827170926_InitialReadDb")]
    partial class InitialReadDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.domain.ReadModels.CourseRead", b =>
                {
                    b.Property<string>("Course_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Course_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Course_id");

                    b.ToTable("CoursesRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.CourseStudentRead", b =>
                {
                    b.Property<string>("Student_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Course_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Student_id", "Course_id");

                    b.ToTable("EnrollmentsRead");
                });

            modelBuilder.Entity("App.domain.ReadModels.StudentRead", b =>
                {
                    b.Property<string>("Student_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_id");

                    b.ToTable("StudentsRead");
                });
#pragma warning restore 612, 618
        }
    }
}
