// <auto-generated />
using System;
using App.infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.infra.Persistence.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827182514_AddCourseContent")]
    partial class AddCourseContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.domain.entity.Course", b =>
                {
                    b.Property<string>("Course_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Course_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Course_id");

                    b.HasIndex("Instructor_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("App.domain.entity.CourseContent", b =>
                {
                    b.Property<string>("Content_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Content_id");

                    b.HasIndex("Course_id");

                    b.ToTable("CourseContents");
                });

            modelBuilder.Entity("App.domain.entity.Course_student", b =>
                {
                    b.Property<string>("Student_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Course_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Student_id", "Course_id");

                    b.HasIndex("Course_id");

                    b.ToTable("CourseStudents");
                });

            modelBuilder.Entity("App.domain.entity.DomainEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DomainEvents");
                });

            modelBuilder.Entity("App.domain.entity.Instructor", b =>
                {
                    b.Property<string>("Instructor_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Instructor_id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("App.domain.entity.Student", b =>
                {
                    b.Property<string>("Student_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("App.domain.entity.Course", b =>
                {
                    b.HasOne("App.domain.entity.Instructor", null)
                        .WithMany()
                        .HasForeignKey("Instructor_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("App.domain.entity.CourseContent", b =>
                {
                    b.HasOne("App.domain.entity.Course", null)
                        .WithMany()
                        .HasForeignKey("Course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.domain.entity.Course_student", b =>
                {
                    b.HasOne("App.domain.entity.Course", null)
                        .WithMany()
                        .HasForeignKey("Course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.domain.entity.Student", null)
                        .WithMany()
                        .HasForeignKey("Student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
